on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  run_issue_code_job:
    runs-on: ubuntu-latest
    name: A job to run code chunks submitted in new issue comments.
    # To use this repository's private action, you must check out the repository
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    # This step references the directory that contains the action.
    - name: run
      uses: ./
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.run.outputs.time }}"
